### ISSUE TITLE
onBubbleRemoved function does not appear to be in v0.2.5

### ISSUE THREAD

**Issue by DaleB-1** [tuxxon/Bubble-Picker#1]
I've updated my app gradle file with:

implementation 'com.github.igalata:Bubble-Picker:v0.2.5'

but I get an error in my MainActivity file which suggests that the function onBubbleRemoved is not present

![image](https://user-images.githubusercontent.com/19421650/100596811-8c993200-3337-11eb-96d0-62122d5b7956.png)

**Comment by tuxxon** [comment]
@DaleB-1  I am so sorry. 

This branch does not follow the previous library system.
I recommend you just have to clone Git source, extract the library - bubble-picker from this project.

I don't know how to follow the previous library system at the moment with this project.

-- Gordon Ahn.

**Comment by tuxxon** [comment]
Do not use this library yet. 
I found some bugs when removing bodies from the world in jbox2d

**Comment by tuxxon** [comment]
This project works normally.
