### ISSUE TITLE
Is this version ready as a library to integrate in my project?

### ISSUE THREAD

**Issue by thaiquoctoanvn** [tuxxon/Bubble-Picker#3]

**Comment by tuxxon** [comment]
I think you may use this one if you don't mind.

**Comment by thaiquoctoanvn** [comment]
@tuxxon Yup, thank you. One more question. Could you please give me the implementation id to this repository or update it in the readme file?

**Comment by tuxxon** [comment]
implementation Id? 
what is that?
I don't know what it is, why do you need it?

**Comment by thaiquoctoanvn** [comment]
Oh sorry for my poor language, i mean something like this **implementation 'com.airbnb.android:lottie:$lottieVersion'**  to integrate your repo in my project

**Comment by tuxxon** [comment]
I got it.
I didn't make the id for implementation or library.

I think you can import the source of buble/picker.

I am sorry for that.

**Comment by thaiquoctoanvn** [comment]
Don’t worry. I will import your repo to my project directly and see what is going. I think everything will work fine.

Hope to see this coming as a library in the future. Thank you

**Comment by tuxxon** [comment]
Ok. I will do it later.

**Comment by uiabhishek15** [comment]
@tuxxon can I add or update a pickeritem using the button, can you provide the source code?

**Comment by tuxxon** [comment]
@uiabhishek15 You can use this source code freely.
